# Generated by Django 4.2.5 on 2023-09-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_api', '0002_myuser_is_buyer_myuser_is_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='aa', max_length=255),
            preserve_default=False,
        ),
    ]
