# Generated by Django 4.2.5 on 2023-09-07 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_api', '0004_product_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sellerProduct',
            new_name='seller',
        ),
    ]
