# Generated by Django 4.2.5 on 2023-09-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_api', '0006_alter_myuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
